### ISSUE TITLE
Sqlite write error when packaging project using pyinstaller in this way.

### ISSUE THREAD

**Issue by EdizCinbas** [Abdur-rahmaanJ/PyQt5_CRUD#1]
Hi,
I recently wrote an application and used pyinstaller in the same way to package it. But while the database opens and everything inside gets displayed, the functions to write data into the database fails. It says database is read-only. I am using MacOS but I don't know if that is the difference maker. Do you know how I can make the database read and write within pyinstaller.

**Comment by Abdur-rahmaanJ** [comment]
@EdizCinbas This smells like a permission issue to me rather than a Python one.
